#!/bin/sh

set -e

release_dir="$(dirname "$0")/target/riscv32ec-unknown-none-elf/release/"

cargo build --release
riscv64-elf-objcopy -R .storage -O binary \
	"$release_dir/fsei-xmas-card-25" \
	"$release_dir/fsei-xmas-card-25.bin"

exec "$(dirname "$0")/../../minichlink" -w "$release_dir/fsei-xmas-card-25.bin" flash -b
